### ISSUE TITLE
Segfault with current Remmina gtk3 branch

### ISSUE THREAD

**Issue by whereisaaron** [muflone/remmina-plugin-rdesktop#2]
Hi @muflone love the plugin, thanks for making it.

The pre-built .deb package works fine for me with the current Ubuntu release of Remmina.

But when I tried using it with the latest Remmina + XFreeRDP built from Github, it dies with a segfault.

I also building the plug-in from source, which was successful, but the resulting plugin also dies with current Remmina (gtk3 branch).

Sorry I don't have more debugging info to share. It might be related to the addition/absence of `freerdp_channels_global_init()` in the plugin API, but that is just a guess.

**Comment by muflone** [comment]
fixed with the GTK+ 3 rewrite
