### ISSUE TITLE
remmina crash

### ISSUE THREAD

**Issue by LetArch** [muflone/remmina-plugin-rdesktop#5]
OS 
Calculate Linux Desktop 15.17 MATE

remmina version
1.2.0-rcgit.3

/var/log/messages contain's
kernel: remmina[4562]: segfault at 140 ip 0000000000434a9a sp 00007ffd12e51f80 error 6 in remmina[400000+4a000]

[remmina]
sharefolder=MY/SHARE/FOLDER
sound=off
name=terminal rdesktop
console=0
ssh_enabled=0
exec=
clientname=
noencryption=0
bitmapcaching=0
server=IPMYSERV
colordepth=16
ssh_auth=0
group=
username=MYUSERNAME
ssh_loopback=0
hidedecorations=0
password=
syncnumlock=0
ssh_username=
execpath=
experience=
title=
resolution=
domain=MYDOMAIN
keymap=
detached=0
nograbkeyboard=0
compression=0
precommand=
nomousemotion=0
seamlessrdpshell=
ssh_server=
protocol=RDESKTOP
seamlessrdp=0
fullscreen=0
ssh_privatekey=
rdp5=0
rdp4=0

**Comment by muflone** [comment]
this was fixed in version 1.3.0.0
